(function(){
'use strict';
var app=document.getElementById('app');
var KEY=window.FONELY_STORAGE_KEY||'fonely_clean_v1';
var state={page:'inicio',patient:null,agendaMode:'mes',agendaDate:dateKey(new Date()),financePatient:null};
var data=load();
function blank(){return {patients:[],appointments:[],payments:[],packages:[],assessments:[],evolutions:[],reports:[],team:[]};}
function load(){try{var d=JSON.parse(localStorage.getItem(KEY))||blank();return d;}catch(e){return blank();}}
['patients','appointments','payments','packages','assessments','evolutions','reports','team'].forEach(function(k){if(!Array.isArray(data[k]))data[k]=[];});
data.patients.forEach(function(p){if(!Array.isArray(p.documents))p.documents=[];if(!p.anamnesis)p.anamnesis={};});
function save(){localStorage.setItem(KEY,JSON.stringify(data));if(window.FonelyCloud)window.FonelyCloud.saveWorkspace(data);}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7);}
function dateKey(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function parseDate(s){var p=(s||'').split('-').map(Number);return new Date(p[0]||2000,(p[1]||1)-1,p[2]||1,12,0,0);}
function today(){return dateKey(new Date());}
function shortDate(s){return s?parseDate(s).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit'}):'—';}
function patientAge(p){if(!p||!p.birth)return '';var b=parseDate(p.birth),n=new Date(),a=n.getFullYear()-b.getFullYear(),m=n.getMonth()-b.getMonth();if(m<0||(m===0&&n.getDate()<b.getDate()))a--;return a>=0?a+' ano'+(a===1?'':'s'):'';}
function nextAppointment(pid){return data.appointments.filter(function(a){return a.patientId===pid&&a.date>=today()&&['Cancelado','Concluído','Faltou'].indexOf(a.status)<0;}).sort(function(a,b){return ((a.date||'')+(a.time||'')).localeCompare((b.date||'')+(b.time||''));})[0]||null;}
function lastEvolution(pid){return data.evolutions.filter(function(x){return x.patientId===pid;}).sort(function(a,b){return (b.date||'').localeCompare(a.date||'');})[0]||null;}
function monthKey(s){return String(s||'').slice(0,7);}
function monthRevenue(){var mk=today().slice(0,7);return data.payments.filter(function(p){return p.status==='Pago'&&monthKey(p.date)===mk;}).reduce(function(sum,p){return sum+Number(p.value||0);},0);}
function money(v){return 'R$ '+Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});}
function slug(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'');}
function areaKey(area){var x=slug(area);if(x.indexOf('linguagem')>=0)return 'linguagem';if(x.indexOf('fonologia')>=0||x==='fala')return 'fala';if(x.indexOf('voz')>=0)return 'voz';if(x.indexOf('fluencia')>=0)return 'fluencia';if(x.indexOf('motricidade')>=0)return 'mo';if(x.indexOf('disfagia')>=0)return 'disfagia';if(x.indexOf('audiologia')>=0)return 'audio';if(x.indexOf('caa')>=0)return 'caa';return 'outra';}
function areaTag(area){area=area||'Fonoaudiologia';return '<mark class="farea-tag area-'+areaKey(area)+'">'+esc(area)+'</mark>';}
function teamContext(){var a=window.FonelyAccount||{};return a.team||{isOwner:true,permissions:{finance:true,reports:true,manage_team:true}};}
function isWorkspaceOwner(){return teamContext().isOwner!==false;}
function canAccess(key){var t=teamContext();if(t.isOwner!==false)return true;return !!(t.permissions&&t.permissions[key]);}
function currentProfessional(){var a=window.FonelyAccount||{},p=a.profile||{},u=a.user||{},t=a.team||{};return {id:u.id||'',name:p.full_name||String(u.email||'Profissional').split('@')[0]||'Profissional',email:u.email||p.email||'',role:t.role||'Profissional'};}
function recordProfessional(x){return x&&((x.professionalName||x.professional)||'')||'';}
function professionalMetaHTML(x){var n=recordProfessional(x);return n?'<small class="record-professional">Profissional: '+esc(n)+'</small>':'';}
function canOpenPage(page){if(page==='financeiro')return canAccess('finance');if(page==='relatorios')return canAccess('reports');if(page==='equipe')return isWorkspaceOwner()||canAccess('manage_team');return true;}


function logo(){return '<div class="brand"><img class="fonely-official-logo" src="fonely-logo-official.svg" alt="Fonely"></div>';}
var nav=[['inicio','⌂','Início'],['agenda','▣','Agenda'],['pacientes','♡','Pacientes'],['avaliacoes','◇','Avaliações'],['evolucoes','✎','Evoluções'],['documentos','▤','Documentos'],['financeiro','$','Financeiro'],['relatorios','◫','Relatórios'],['equipe','♙','Equipe']];
function shell(body,title,action){
  var account=window.FonelyAccount||{},profile=account.profile||{},access=account.access||{},user=account.user||{},team=account.team||{};
  var accountName=profile.full_name||String(user.email||'Meu espaço').split('@')[0]||'Meu espaço';
  var accountInitial=(accountName||'F').charAt(0).toUpperCase();
  var accountPlan=team.isOwner===false?(team.role||'Membro da equipe'):(access.plan_tier==='pro'?'Fonely Pro':'Fonely Básico');
  var avatar=profile.avatar_url
    ?'<span class="top-account-avatar"><img data-profile-avatar src="'+esc(profile.avatar_url)+'" alt=""></span>'
    :'<span class="top-account-avatar fallback" data-profile-avatar-fallback>'+esc(accountInitial)+'</span>';
  var accountMenu='<button class="top-account" id="accountMenu" type="button" aria-label="Abrir minha conta">'+avatar+'<span class="top-account-copy"><b>'+esc(accountName)+'</b><small>'+esc(accountPlan)+'</small></span><i>⌄</i></button>';
  return '<div class="layout"><aside>'+logo()+'<nav>'+nav.filter(function(n){return canOpenPage(n[0]);}).map(function(n){return '<button data-go="'+n[0]+'" class="'+(state.page===n[0]?'active':'')+'"><i>'+n[1]+'</i>'+n[2]+'</button>';}).join('')+'<button data-go="academy"><i>✦</i>Fonely Academy <em>EM BREVE</em></button></nav></aside><main><header><div><small class="overline">FONELY</small><h1>'+esc(title||'')+'</h1></div><div class="header-actions">'+(action||'')+accountMenu+'</div></header>'+body+'</main></div>';
}
function render(){if(!canOpenPage(state.page))state.page='inicio';var fn={inicio:home,agenda:agenda,pacientes:patients,avaliacoes:assessmentsPage,evolucoes:evolutionsPage,documentos:documentsPage,financeiro:finance,relatorios:reportsPage,equipe:teamPage,academy:academy}[state.page]||home;app.innerHTML=fn();bind();}
function patient(pid){return data.patients.find(function(x){return x.id===pid;});}
function patientName(pid){var p=patient(pid);return p?p.name:'Paciente';}
function activePackage(pid){return data.packages.filter(function(p){return p.patientId===pid&&p.status!=='Encerrado'&&Number(p.used||0)<Number(p.sessions||0);}).sort(function(a,b){return (b.startDate||'').localeCompare(a.startDate||'');})[0]||null;}
function remainingPackage(pkg){return Math.max(0,Number(pkg.sessions||0)-Number(pkg.used||0));}
function recalcPackage(pkg){var used=data.appointments.filter(function(a){return a.packageId===pkg.id&&a.status==='Concluído';}).length;pkg.used=used;pkg.status=used>=Number(pkg.sessions||0)?'Encerrado':'Ativo';}
function syncPackages(){data.packages.forEach(recalcPackage);}
function appointmentsForDate(date){return data.appointments.filter(function(a){return a.date===date;}).sort(function(a,b){return (a.time||'').localeCompare(b.time||'');});}
function home(){
  syncPackages();
  var aps=appointmentsForDate(today()),doneList=aps.filter(function(a){return a.status==='Concluído';}),done=doneList.length,
  confirmed=aps.filter(function(a){return a.status==='Confirmado';}).length,
  pendingEvol=doneList.filter(function(a){return !data.evolutions.some(function(e){return e.appointmentId===a.id;});}).length,
  activeToday=aps.filter(function(a){return ['Cancelado','Concluído','Faltou'].indexOf(a.status)<0;}),
  next=activeToday[0]||null,
  quickPatients=data.patients.slice().sort(function(a,b){var an=nextAppointment(a.id),bn=nextAppointment(b.id);return ((an&&an.date)||'9999').localeCompare((bn&&bn.date)||'9999');}).slice(0,5),
  dayLabel=parseDate(today()).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'}),
  pro=currentProfessional(),
  myRecords=data.evolutions.filter(function(x){return x.professionalId===pro.id;}).length;
  var fourthStat=canAccess('finance')
    ?'<button class="fhome-stat" data-home-go="financeiro"><i>$</i><small>RECEBIDO NO MÊS</small><b class="money">'+money(monthRevenue())+'</b><span>Financeiro do Fonely</span><em>Abrir financeiro →</em></button>'
    :'<button class="fhome-stat" data-home-go="evolucoes"><i>✎</i><small>MEUS REGISTROS</small><b>'+myRecords+'</b><span>Evoluções registradas por você</span><em>Abrir evoluções →</em></button>';
  return shell(
    '<section class="fhome-welcome"><div><span class="fhome-kicker">VISÃO DO DIA</span><h2>Seu consultório em ordem.</h2><p>Agenda, pacientes e registros clínicos conectados em um único fluxo.</p></div><button id="homeNewAppointment" class="primary">+ Novo atendimento</button></section>'+
    '<div class="fhome-stats"><button class="fhome-stat" data-home-list="today"><i>▣</i><small>ATENDIMENTOS HOJE</small><b>'+aps.length+'</b><span>'+confirmed+' confirmado'+(confirmed===1?'':'s')+'</span><em>Ver atendimentos →</em></button><button class="fhome-stat" data-home-list="done"><i>✓</i><small>CONCLUÍDOS HOJE</small><b>'+done+'</b><span>'+pendingEvol+' evolução'+(pendingEvol===1?'':'ões')+' pendente'+(pendingEvol===1?'':'s')+'</span><em>Ver concluídos →</em></button><button class="fhome-stat" data-home-go="pacientes"><i>♡</i><small>PACIENTES</small><b>'+data.patients.length+'</b><span>'+data.assessments.length+' avaliações registradas</span><em>Ver pacientes →</em></button>'+fourthStat+'</div>'+
    '<div class="fhome-main"><article class="panel fhome-agenda"><div class="panel-title"><div><small>AGENDA DE HOJE · '+esc(dayLabel.toUpperCase())+'</small><h3>'+(next?'Próximo: '+esc(next.time||'')+' · '+esc(patientName(next.patientId)):(aps.length?'Todos os horários de hoje finalizados':'Agenda livre hoje'))+'</h3></div><button data-go="agenda">Abrir agenda →</button></div>'+
    (aps.length?'<div class="fhome-upcoming">'+aps.map(function(a){return '<button data-ap="'+a.id+'"><div class="fhome-date"><b>'+esc(a.time||'—')+'</b><span>'+esc(a.duration?a.duration+' min':'Hoje')+'</span></div><div><strong>'+esc(patientName(a.patientId))+'</strong><small>'+esc(a.type||'Atendimento')+' · '+esc(a.mode||'Presencial')+'</small></div><mark class="status-'+slug(a.status)+'">'+esc(a.status||'Agendado')+'</mark></button>';}).join('')+'</div>':'<div class="empty"><b>Nenhum horário hoje</b><span>Adicione um atendimento ou abra a agenda para consultar outros dias.</span></div>')+
    '</article><article class="panel fhome-patients"><div class="panel-title"><div><small>PACIENTES</small><h3>Acesso rápido</h3></div><button data-go="pacientes">Ver todos →</button></div>'+
    (quickPatients.length?'<div class="fhome-patient-list">'+quickPatients.map(function(p){var na=nextAppointment(p.id);return '<button data-patient="'+p.id+'"><div class="avatar">'+esc((p.name||'?').charAt(0))+'</div><div><b>'+esc(p.name)+'</b><span>'+areaTag(p.area)+(na?' · '+shortDate(na.date)+' '+esc(na.time||''):' · sem próximo horário')+'</span></div><strong>→</strong></button>';}).join('')+'</div>':'<div class="empty"><b>Nenhum paciente cadastrado</b></div>')+
    '</article></div><article class="panel fhome-alerts"><div class="panel-title"><div><small>ATENÇÃO</small><h3>O que merece olhar hoje</h3></div></div>'+alerts()+'</article>',
    'Início',''
  );
}
function alerts(){var arr=[];data.packages.forEach(function(p){var r=remainingPackage(p);if(p.status!=='Encerrado'&&r<=2)arr.push('<div class="alert"><b>'+esc(patientName(p.patientId))+'</b><span>Pacote com '+r+' sessão'+(r===1?'':'ões')+' restante'+(r===1?'':'s')+'.</span></div>');});data.payments.filter(function(p){return p.status==='Pendente';}).slice(0,3).forEach(function(p){arr.push('<div class="alert warn"><b>Pagamento pendente · '+esc(patientName(p.patientId))+'</b><span>'+money(p.value)+' · '+shortDate(p.date)+'</span></div>');});return arr.length?arr.join(''):'<div class="alert"><b>Tudo organizado ✦</b><span>Sem alertas importantes neste momento.</span></div>';}
function appointmentRows(list){if(!list.length)return '<div class="empty"><b>Nenhum atendimento</b><span>Use a agenda para adicionar um horário.</span></div>';return '<div class="rows">'+list.map(function(a){var pkg=a.packageId?data.packages.find(function(p){return p.id===a.packageId;}):null;return '<button class="row appointment-row" data-ap="'+a.id+'"><div class="time">'+esc(a.time||'—')+'</div><div><b>'+esc(patientName(a.patientId))+'</b><span>'+esc(a.type||'Atendimento')+' · '+esc(a.mode||'Presencial')+(pkg?' · Pacote '+remainingPackage(pkg)+' restantes':'')+'</span></div><mark class="status-'+slug(a.status)+'">'+esc(a.status||'Agendado')+'</mark></button>';}).join('')+'</div>';}
function patients(){
  var areas={};data.patients.forEach(function(p){areas[p.area||'Fonoaudiologia']=(areas[p.area||'Fonoaudiologia']||0)+1;});
  var topArea=Object.keys(areas).sort(function(a,b){return areas[b]-areas[a];})[0]||'—';
  return shell('<div class="fpatients-summary"><div><small>TOTAL</small><b>'+data.patients.length+'</b><span>pacientes cadastrados</span></div><div><small>COM PRÓXIMO HORÁRIO</small><b>'+data.patients.filter(function(p){return !!nextAppointment(p.id);}).length+'</b><span>acompanhamentos ativos</span></div><div><small>ÁREA MAIS FREQUENTE</small><b class="text">'+esc(topArea)+'</b><span>na sua carteira atual</span></div></div><article class="panel"><div class="tools"><input id="patientSearch" placeholder="Buscar por nome, área ou responsável"><button id="newPatient" class="primary">+ Novo paciente</button></div><div id="patientList">'+patientList(data.patients)+'</div></article>','Pacientes','');
}
function patientList(list){
  if(!list.length)return '<div class="empty"><b>Nenhum paciente encontrado</b><span>Cadastre um novo paciente ou altere a busca.</span></div>';
  return '<div class="patient-list">'+list.map(function(p){var pkg=activePackage(p.id),na=nextAppointment(p.id),le=lastEvolution(p.id);return '<button class="patient fpatient-row" data-patient="'+p.id+'"><div class="avatar">'+esc((p.name||'?').charAt(0))+'</div><div class="fpatient-main"><b>'+esc(p.name)+'</b><span>'+esc(p.area||'Fonoaudiologia')+(patientAge(p)?' · '+patientAge(p):'')+(p.guardian?' · Resp. '+esc(p.guardian):'')+'</span><small>'+(na?'Próximo: '+shortDate(na.date)+' às '+esc(na.time||''):(le?'Última evolução: '+shortDate(le.date):'Sem atendimento agendado'))+'</small></div><div class="fpatient-side">'+(pkg?'<em>'+remainingPackage(pkg)+' sessões</em>':'')+'<strong>→</strong></div></button>';}).join('')+'</div>';
}
function patientView(p){
  syncPackages();
  var pkg=activePackage(p.id),ass=data.assessments.filter(function(x){return x.patientId===p.id;}).length,
  evs=data.evolutions.filter(function(x){return x.patientId===p.id;}).sort(function(a,b){return (b.date||'').localeCompare(a.date||'');}),
  ev=evs.length,docs=(p.documents||[]).length,na=nextAppointment(p.id),le=evs[0]||null;
  var cards=[['anam','📝','Anamnese','Histórico inicial, desenvolvimento e rotina'],['assess','◇','Avaliações','Avaliação inicial, triagem e reavaliações'],['evol','✎','Evoluções','Registro clínico de cada sessão'],['docs','▤','Documentos','Laudos, exames, fotos, vídeos e amostras']];
  if(canAccess('finance'))cards.push(['fin','$','Financeiro','Pacotes, sessões e pagamentos']);
  if(canAccess('reports'))cards.push(['reports','◫','Relatórios','Indicadores e acompanhamento do caso']);
  return shell('<button class="back" data-go="pacientes">← Voltar aos pacientes</button><article class="patient-head fpatient-head"><div class="avatar large">'+esc((p.name||'?').charAt(0))+'</div><div class="fpatient-title"><small>PACIENTE</small><h2>'+esc(p.name)+'</h2><p>'+esc(p.area||'Área não informada')+(patientAge(p)?' · '+patientAge(p):'')+(p.guardian?' · Responsável: '+esc(p.guardian):'')+'</p>'+(p.complaint?'<span class="fpatient-complaint">'+esc(p.complaint)+'</span>':'')+'</div><button class="primary" id="schedulePatient">+ Agendar</button></article>'+
  '<div class="fpatient-context"><div><small>PRÓXIMO ATENDIMENTO</small><b>'+(na?shortDate(na.date)+' · '+esc(na.time||'—'):'Não agendado')+'</b><span>'+(na?esc(na.type||'Atendimento')+' · '+esc(na.mode||'Presencial'):'Use “Agendar” para criar um horário')+'</span></div><div><small>ÚLTIMO REGISTRO</small><b>'+(le?shortDate(le.date):'Sem evolução')+'</b><span>'+(le?esc(le.focus||'Sessão clínica')+(recordProfessional(le)?' · '+esc(recordProfessional(le)):''):'Registre a primeira evolução')+'</span></div><div><small>PACOTE ATIVO</small><b>'+(pkg?remainingPackage(pkg)+' de '+Number(pkg.sessions||0)+' restantes':'Sem pacote')+'</b><span>'+(pkg?esc(pkg.name||'Pacote'):'Atendimento avulso ou sem pacote')+'</span></div></div>'+
  '<div class="fpatient-actions"><button id="patientNewAssessment"><i>◇</i><span><b>Nova avaliação</b><small>Registrar avaliação ou reavaliação</small></span></button><button id="patientNewEvolution"><i>✎</i><span><b>Nova evolução</b><small>Registrar a sessão de hoje</small></span></button><button id="patientNewDocument"><i>▤</i><span><b>Novo documento</b><small>Anexar material clínico</small></span></button></div>'+
  '<div class="patient-kpis"><div><b>'+ass+'</b><span>Avaliações</span></div><div><b>'+ev+'</b><span>Evoluções</span></div><div><b>'+docs+'</b><span>Documentos</span></div><div><b>'+(pkg?remainingPackage(pkg):'—')+'</b><span>Sessões restantes</span></div></div><div class="clinical-grid">'+cards.map(function(x){return '<button class="clinical" data-parea="'+x[0]+'"><i>'+x[1]+'</i><b>'+x[2]+'</b><span>'+x[3]+'</span></button>';}).join('')+'</div>','Prontuário','');
}
function agenda(){
  var base=parseDate(state.agendaDate),y=base.getFullYear(),m=base.getMonth(),first=new Date(y,m,1,12),last=new Date(y,m+1,0,12),offset=(first.getDay()+6)%7,cells=[];
  for(var i=0;i<offset;i++)cells.push(null);
  for(var day=1;day<=last.getDate();day++)cells.push(dateKey(new Date(y,m,day,12)));
  while(cells.length%7)cells.push(null);
  var title=base.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}),mk=dateKey(base).slice(0,7);
  var monthAps=data.appointments.filter(function(a){return monthKey(a.date)===mk;});
  var monthDone=monthAps.filter(function(a){return a.status==='Concluído';}).length;
  var monthMiss=monthAps.filter(function(a){return a.status==='Faltou';}).length;
  var future=data.appointments.filter(function(a){return a.date>=today()&&['Cancelado','Concluído','Faltou'].indexOf(a.status)<0;}).sort(function(a,b){return ((a.date||'')+(a.time||'')).localeCompare((b.date||'')+(b.time||''));}).slice(0,8);
  var html='<section class="agenda-top"><div class="agenda-nav"><button id="agendaPrev" class="icon-btn">‹</button><button id="agendaToday" class="soft-btn">Hoje</button><button id="agendaNext" class="icon-btn">›</button><div><b>'+esc(title.charAt(0).toUpperCase()+title.slice(1))+'</b><span>Clique em um dia para ver os atendimentos</span></div></div><button id="newAppointment" class="primary">+ Novo agendamento</button></section>'+
  '<div class="fagenda-stats"><div><small>NO MÊS</small><b>'+monthAps.length+'</b><span>agendamentos</span></div><div><small>CONCLUÍDOS</small><b>'+monthDone+'</b><span>atendimentos</span></div><div><small>FALTAS</small><b>'+monthMiss+'</b><span>registradas</span></div></div>'+
  '<div class="fagenda-layout"><article class="agenda-board"><div class="month-weekdays"><span>SEG</span><span>TER</span><span>QUA</span><span>QUI</span><span>SEX</span><span>SÁB</span><span>DOM</span></div><div class="month-grid">'+cells.map(function(d){if(!d)return '<div class="month-cell muted-cell"></div>';var list=appointmentsForDate(d);return '<button class="month-cell '+(d===today()?'is-today':'')+'" data-day="'+d+'"><b>'+parseDate(d).getDate()+'</b>'+list.slice(0,4).map(function(a){return '<span class="mini-'+slug(a.status)+'"><i>'+esc(a.time||'')+'</i> '+esc(patientName(a.patientId))+'</span>';}).join('')+(list.length>4?'<em>+'+(list.length-4)+' atendimento(s)</em>':'')+'</button>';}).join('')+'</div></article>'+
  '<aside class="panel fagenda-next"><div class="panel-title"><div><small>PRÓXIMOS</small><h3>Agenda futura</h3></div></div>'+(future.length?future.map(function(a){return '<button class="fagenda-next-row" data-ap="'+a.id+'"><div><b>'+shortDate(a.date)+'</b><span>'+esc(a.time||'—')+'</span></div><div><strong>'+esc(patientName(a.patientId))+'</strong><small>'+esc(a.type||'Atendimento')+(a.duration?' · '+a.duration+' min':'')+'</small></div></button>';}).join(''):'<div class="empty"><b>Sem próximos horários</b></div>')+'</aside></div>';
  return shell(html,'Agenda','');
}
function dayModal(date){var list=appointmentsForDate(date);modal('<small class="overline">AGENDA DO DIA</small><h2>'+esc(parseDate(date).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'}))+'</h2>'+appointmentRows(list)+'<div class="modal-actions"><button class="primary" id="addOnDay">+ Adicionar atendimento</button></div>');document.getElementById('addOnDay').onclick=function(){document.getElementById('modal').remove();newAppointment(null,date);};bindModalRows();}
function patientOptions(selected){return data.patients.map(function(p){return '<option value="'+p.id+'" '+(selected===p.id?'selected':'')+'>'+esc(p.name)+'</option>';}).join('');}
function packageOptions(pid,selected){var pkgs=data.packages.filter(function(p){return p.patientId===pid&&p.status!=='Encerrado';});return '<option value="">Sem pacote</option>'+pkgs.map(function(p){return '<option value="'+p.id+'" '+(selected===p.id?'selected':'')+'>'+esc(p.name||'Pacote')+' · '+remainingPackage(p)+' restantes</option>';}).join('');}
function newAppointment(preselected,presetDate){
  if(!data.patients.length){newPatient(true);return;}
  var pid=preselected||data.patients[0].id;
  modal('<small class="overline">AGENDA</small><h2>Novo agendamento</h2><form id="appointmentForm"><label>Paciente<select name="patientId" id="appointmentPatient">'+patientOptions(pid)+'</select></label><div class="two"><label>Data<input type="date" name="date" value="'+esc(presetDate||today())+'" required></label><label>Horário<input type="time" name="time" required></label></div><div class="three fappointment-three"><label>Tipo<select name="type"><option>Atendimento</option><option>Avaliação</option><option>Reavaliação</option><option>Triagem</option><option>Orientação familiar</option><option>CAA / comunicação</option></select></label><label>Modalidade<select name="mode"><option>Presencial</option><option>Online</option><option>Domiciliar</option></select></label><label>Duração<select name="duration"><option value="30">30 min</option><option value="40">40 min</option><option value="50" selected>50 min</option><option value="60">60 min</option><option value="90">90 min</option></select></label></div><label>Pacote / forma<select name="packageId" id="appointmentPackage">'+packageOptions(pid,'')+'</select></label><div class="two"><label>Repetição<select name="repeat"><option value="1">Somente este atendimento</option><option value="4">Semanal · 4 sessões</option><option value="8">Semanal · 8 sessões</option><option value="10">Semanal · 10 sessões</option><option value="12">Semanal · 12 sessões</option></select></label><label>Status inicial<select name="status"><option>Agendado</option><option>Confirmado</option></select></label></div><label>Observações<textarea name="notes" placeholder="Objetivo do horário, orientações ou observações importantes"></textarea></label><button class="primary">Salvar agendamento</button></form>');
  document.getElementById('appointmentPatient').onchange=function(){document.getElementById('appointmentPackage').innerHTML=packageOptions(this.value,'');};
  document.getElementById('appointmentForm').onsubmit=function(e){e.preventDefault();var fd=new FormData(e.target),count=Number(fd.get('repeat')||1),start=parseDate(fd.get('date')),series=count>1?'series-'+Date.now():null;for(var n=0;n<count;n++){var d=new Date(start);d.setDate(d.getDate()+(n*7));data.appointments.push({id:id(),patientId:fd.get('patientId'),date:dateKey(d),time:fd.get('time'),type:fd.get('type'),mode:fd.get('mode'),duration:Number(fd.get('duration')||50),packageId:fd.get('packageId')||null,notes:fd.get('notes'),status:fd.get('status')||'Agendado',seriesId:series});}syncPackages();save();document.getElementById('modal').remove();state.page='agenda';state.agendaDate=fd.get('date');render();};
}
function appointmentDetails(a){
  var pkg=a.packageId?data.packages.find(function(p){return p.id===a.packageId;}):null;
  modal('<small class="overline">ATENDIMENTO</small><h2>'+esc(patientName(a.patientId))+'</h2><div class="appointment-detail"><div><small>DATA E HORÁRIO</small><b>'+shortDate(a.date)+' · '+esc(a.time||'—')+'</b></div><div><small>TIPO</small><b>'+esc(a.type||'Atendimento')+'</b></div><div><small>MODALIDADE</small><b>'+esc(a.mode||'Presencial')+(a.duration?' · '+a.duration+' min':'')+'</b></div><div><small>PACOTE</small><b>'+(pkg?esc(pkg.name||'Pacote')+' · '+remainingPackage(pkg)+' restantes':'Sem pacote')+'</b></div></div>'+(a.notes?'<div class="detail-note">'+esc(a.notes)+'</div>':'')+'<label>Status<select id="apStatus"><option '+sel(a.status,'Agendado')+'>Agendado</option><option '+sel(a.status,'Confirmado')+'>Confirmado</option><option '+sel(a.status,'Concluído')+'>Concluído</option><option '+sel(a.status,'Faltou')+'>Faltou</option><option '+sel(a.status,'Cancelado')+'>Cancelado</option><option '+sel(a.status,'Reagendado')+'>Reagendado</option></select></label><div class="modal-actions"><button id="saveStatus" class="primary">Salvar status</button><button id="createEvolutionFromAppointment" class="soft-btn">Registrar evolução</button><button id="editAppointment" class="soft-btn">Editar</button><button id="deleteAppointment" class="danger-btn">Excluir</button></div>');
  document.getElementById('saveStatus').onclick=function(){var newStatus=document.getElementById('apStatus').value;a.status=newStatus;syncPackages();save();document.getElementById('modal').remove();var hasEvolution=data.evolutions.some(function(e){return e.appointmentId===a.id;});if(newStatus==='Concluído'&&!hasEvolution){evolutionForm(a.patientId,a);}else render();};
  document.getElementById('createEvolutionFromAppointment').onclick=function(){document.getElementById('modal').remove();evolutionForm(a.patientId,a);};
  document.getElementById('editAppointment').onclick=function(){document.getElementById('modal').remove();editAppointment(a);};
  document.getElementById('deleteAppointment').onclick=function(){if(confirm('Excluir este agendamento?')){data.appointments=data.appointments.filter(function(x){return x.id!==a.id;});syncPackages();save();document.getElementById('modal').remove();render();}};
}
function editAppointment(a){
  modal('<small class="overline">AGENDA</small><h2>Editar agendamento</h2><form id="editAppointmentForm"><label>Paciente<select name="patientId" id="editPatient">'+patientOptions(a.patientId)+'</select></label><div class="two"><label>Data<input type="date" name="date" value="'+esc(a.date)+'" required></label><label>Horário<input type="time" name="time" value="'+esc(a.time||'')+'" required></label></div><div class="three fappointment-three"><label>Tipo<input name="type" value="'+esc(a.type||'Atendimento')+'"></label><label>Modalidade<select name="mode"><option '+sel(a.mode,'Presencial')+'>Presencial</option><option '+sel(a.mode,'Online')+'>Online</option><option '+sel(a.mode,'Domiciliar')+'>Domiciliar</option></select></label><label>Duração<select name="duration">'+[30,40,50,60,90].map(function(n){return '<option value="'+n+'" '+(Number(a.duration||50)===n?'selected':'')+'>'+n+' min</option>';}).join('')+'</select></label></div><label>Pacote<select name="packageId" id="editPackage">'+packageOptions(a.patientId,a.packageId)+'</select></label><label>Observações<textarea name="notes">'+esc(a.notes||'')+'</textarea></label><button class="primary">Salvar alterações</button></form>');
  document.getElementById('editPatient').onchange=function(){document.getElementById('editPackage').innerHTML=packageOptions(this.value,'');};
  document.getElementById('editAppointmentForm').onsubmit=function(e){e.preventDefault();var fd=new FormData(e.target);a.patientId=fd.get('patientId');a.date=fd.get('date');a.time=fd.get('time');a.type=fd.get('type');a.mode=fd.get('mode');a.duration=Number(fd.get('duration')||50);a.packageId=fd.get('packageId')||null;a.notes=fd.get('notes');syncPackages();save();document.getElementById('modal').remove();render();};
}
function sel(a,b){return a===b?'selected':'';}
function newPatient(fromAgenda){modal('<small class="overline">NOVO CADASTRO</small><h2>Novo paciente</h2><form id="patientForm"><label>Nome completo<input name="name" required></label><div class="two"><label>Data de nascimento<input type="date" name="birth"></label><label>Telefone<input name="phone"></label></div><div class="two"><label>Responsável<input name="guardian"></label><label>Área principal<select name="area"><option>Linguagem</option><option>Fala / Fonologia</option><option>Voz</option><option>Fluência</option><option>Motricidade Orofacial</option><option>Disfagia</option><option>Audiologia</option><option>Outra</option></select></label></div><label>Queixa principal<textarea name="complaint"></textarea></label><button class="primary">Cadastrar paciente</button></form>');document.getElementById('patientForm').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),p={id:id(),name:f.get('name'),birth:f.get('birth'),phone:f.get('phone'),guardian:f.get('guardian'),area:f.get('area'),complaint:f.get('complaint'),anamnesis:{},documents:[]};data.patients.push(p);save();document.getElementById('modal').remove();if(fromAgenda)newAppointment(p.id,state.agendaDate);else{state.patient=p.id;app.innerHTML=patientView(p);bind();}};}
function anamnesis(p){var a=p.anamnesis||{};modal('<small class="overline">PRONTUÁRIO CLÍNICO</small><h2>Anamnese · '+esc(p.name)+'</h2><form id="anamForm"><label>Queixa principal<textarea name="complaint">'+esc(a.complaint||p.complaint||'')+'</textarea></label><label>Gestação, nascimento e desenvolvimento<textarea name="development">'+esc(a.development||'')+'</textarea></label><label>Comunicação, fala e linguagem<textarea name="communication">'+esc(a.communication||'')+'</textarea></label><div class="two"><label>Alimentação / funções orais<textarea name="feeding">'+esc(a.feeding||'')+'</textarea></label><label>Audição / voz<textarea name="hearingVoice">'+esc(a.hearingVoice||'')+'</textarea></label></div><label>Histórico médico / medicamentos / acompanhamentos<textarea name="medical">'+esc(a.medical||'')+'</textarea></label><label>Escola, comportamento, rotina e observações<textarea name="other">'+esc(a.other||'')+'</textarea></label><button class="primary">Salvar anamnese</button></form>');document.getElementById('anamForm').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);p.anamnesis={complaint:f.get('complaint'),development:f.get('development'),communication:f.get('communication'),feeding:f.get('feeding'),hearingVoice:f.get('hearingVoice'),medical:f.get('medical'),other:f.get('other'),updatedAt:today()};p.complaint=f.get('complaint');save();document.getElementById('modal').remove();app.innerHTML=patientView(p);bind();};}
function assessmentsPage(){return clinicalListing('Avaliações','assessment');}
function evolutionsPage(){return clinicalListing('Evoluções','evolution');}
function documentsPage(){
  var docs=[];data.patients.forEach(function(p){(p.documents||[]).forEach(function(d){docs.push({p:p,d:d});});});docs.sort(function(a,b){return (b.d.date||'').localeCompare(a.d.date||'');});
  var samples=docs.filter(function(x){return /Áudio|Vídeo|Foto/i.test(x.d.type||'');}).length,latest=docs[0];
  return shell('<div class="fdocs-summary"><div><small>TOTAL</small><b>'+docs.length+'</b><span>arquivos clínicos</span></div><div><small>AMOSTRAS</small><b>'+samples+'</b><span>áudio, vídeo ou foto</span></div><div><small>ÚLTIMO ARQUIVO</small><b class="text">'+(latest?shortDate(latest.d.date):'—')+'</b><span>'+(latest?esc(latest.p.name):'Nenhum documento')+'</span></div></div><article class="panel"><div class="tools"><div><b>Documentos clínicos</b><span class="muted">Laudos, exames, amostras e registros por paciente</span></div><button id="newGlobalDocument" class="primary">+ Adicionar documento</button></div>'+(docs.length?'<div class="record-list fdocs-list">'+docs.map(function(x){return documentRow(x.p,x.d);}).join('')+'</div>':'<div class="empty"><b>Nenhum documento</b><span>Adicione arquivos a partir daqui ou do prontuário do paciente.</span></div>')+'</article>','Documentos Clínicos','');
}
function clinicalListing(title,type){var arr=type==='assessment'?data.assessments:data.evolutions;var html=arr.slice().sort(function(a,b){return (b.date||'').localeCompare(a.date||'');}).map(function(x){return '<div class="clinical-record"><div><b>'+esc(patientName(x.patientId))+' · '+shortDate(x.date)+'</b><small>'+esc(type==='assessment'?(x.kind||'Avaliação'):(x.focus||'Atendimento'))+'</small><p>'+esc(type==='assessment'?(x.summary||''):(x.text||''))+'</p></div></div>';}).join('');return shell('<article class="panel"><div class="tools"><div><b>'+title+'</b><span class="muted">Histórico de todos os pacientes</span></div><button id="newClinical" data-kind="'+type+'" class="primary">+ Novo registro</button></div>'+(html||'<div class="empty"><b>Nenhum registro</b><span>Crie o primeiro registro clínico.</span></div>')+'</article>',title,'');}
function assessmentArea(p){var list=data.assessments.filter(function(x){return x.patientId===p.id;}).sort(function(a,b){return (b.date||'').localeCompare(a.date||'');});modal('<small class="overline">AVALIAÇÕES</small><h2>'+esc(p.name)+'</h2><div class="modal-actions"><button class="primary" id="newAssessment">+ Nova avaliação</button></div>'+(list.length?'<div class="record-list">'+list.map(function(x){return '<div class="clinical-record"><div><b>'+esc(x.kind||'Avaliação')+'</b><small>'+shortDate(x.date)+' · '+esc(x.area||'Geral')+'</small><p>'+esc(x.summary||'')+'</p></div></div>';}).join('')+'</div>':'<div class="empty">Nenhuma avaliação registrada.</div>'));document.getElementById('newAssessment').onclick=function(){assessmentForm(p.id);};}
function assessmentSpecificFields(area){
  var k=areaKey(area),common='<label>Comportamento durante a avaliação<textarea name="behavior" placeholder="Interação, atenção, participação, vínculo, necessidade de apoio e observações relevantes"></textarea></label>';
  if(k==='linguagem'||k==='caa')return common+'<div class="two"><label>Compreensão / linguagem receptiva<textarea name="receptive" placeholder="Compreensão de ordens, perguntas, conceitos, vocabulário receptivo"></textarea></label><label>Expressão / linguagem expressiva<textarea name="expressive" placeholder="Intenção comunicativa, vocabulário, frases, narrativa e pragmática"></textarea></label></div><div class="two"><label>Pragmática e interação<textarea name="pragmatics" placeholder="Turnos, contato, iniciativa, manutenção de tópico e funções comunicativas"></textarea></label><label>Recursos de comunicação<textarea name="communicationResources" placeholder="Fala, gestos, CAA, pistas, apoios visuais e recursos utilizados"></textarea></label></div>';
  if(k==='fala')return common+'<div class="two"><label>Produção dos sons da fala<textarea name="speechProduction" placeholder="Trocas, omissões, distorções, processos fonológicos e inteligibilidade"></textarea></label><label>Consciência fonológica / discriminação<textarea name="phonology" placeholder="Rimas, sílabas, fonemas, discriminação e habilidades metafonológicas"></textarea></label></div><label>Estruturas e mobilidade orofacial<textarea name="oralMotor" placeholder="Lábios, língua, bochechas, mandíbula e coordenação relacionada à fala"></textarea></label>';
  if(k==='voz')return common+'<div class="two"><label>Qualidade vocal<textarea name="voiceQuality" placeholder="Tipo de voz, rugosidade, soprosidade, tensão, instabilidade e ressonância"></textarea></label><label>Parâmetros vocais<textarea name="voiceParameters" placeholder="Pitch, loudness, ataque, coordenação pneumofonoarticulatória e tempo máximo de fonação"></textarea></label></div><label>Hábitos e demanda vocal<textarea name="voiceHabits" placeholder="Uso profissional, abuso vocal, hidratação, sintomas e fatores associados"></textarea></label>';
  if(k==='fluencia')return common+'<div class="two"><label>Características da fluência<textarea name="fluency" placeholder="Repetições, prolongamentos, bloqueios, velocidade e frequência observada"></textarea></label><label>Comportamentos associados<textarea name="fluencyAssociated" placeholder="Tensão, movimentos associados, evitação, impacto emocional e situações de maior dificuldade"></textarea></label></div>';
  if(k==='mo')return common+'<div class="two"><label>Estruturas orofaciais<textarea name="structures" placeholder="Lábios, língua, bochechas, palato, mandíbula, dentição e postura"></textarea></label><label>Mobilidade / tônus / coordenação<textarea name="mobility" placeholder="Amplitude, força, tônus, precisão e coordenação dos movimentos"></textarea></label></div><label>Funções estomatognáticas<textarea name="functions" placeholder="Respiração, mastigação, deglutição, sucção e fala"></textarea></label>';
  if(k==='disfagia')return common+'<div class="two"><label>Condição alimentar atual<textarea name="feedingStatus" placeholder="Via de alimentação, consistências, utensílios, postura e independência"></textarea></label><label>Sinais clínicos na deglutição<textarea name="swallowSigns" placeholder="Tosse, engasgo, voz molhada, escape, resíduos, fadiga e tempo de refeição"></textarea></label></div><label>Segurança / funcionalidade<textarea name="swallowSafety" placeholder="Achados clínicos, necessidade de adaptação, supervisão e encaminhamentos"></textarea></label>';
  if(k==='audio')return common+'<div class="two"><label>Queixas e histórico auditivo<textarea name="hearingHistory" placeholder="Queixa, otites, exposição a ruído, triagens e exames prévios"></textarea></label><label>Respostas auditivas observadas<textarea name="hearingResponses" placeholder="Detecção, localização, discriminação e compreensão em diferentes contextos"></textarea></label></div>';
  return common+'<label>Aspectos específicos da área<textarea name="specific" placeholder="Registre os achados específicos relevantes para este caso"></textarea></label>';
}
function assessmentForm(pid){
  var p=patient(pid),defaultArea=p&&p.area||'Linguagem';
  modal('<small class="overline">AVALIAÇÃO FONOAUDIOLÓGICA</small><h2>Novo registro</h2><form id="assessmentForm"><div class="two"><label>Tipo<select name="kind"><option>Avaliação inicial</option><option>Reavaliação</option><option>Triagem</option><option>Avaliação complementar</option></select></label><label>Data<input type="date" name="date" value="'+today()+'"></label></div><div class="two"><label>Área principal<select name="area" id="assessmentArea">'+['Linguagem','Fala / Fonologia','Voz','Fluência','Motricidade Orofacial','Disfagia','Audiologia','CAA / Comunicação','Outra'].map(function(x){return '<option '+(x===defaultArea?'selected':'')+'>'+x+'</option>';}).join('')+'</select></label><label>Protocolo / instrumento<input name="protocol" placeholder="Ex.: protocolo, escala ou avaliação clínica"></label></div><label>Motivo / objetivo da avaliação<textarea name="objective" placeholder="Queixa, demanda principal e o que está sendo investigado ou acompanhado"></textarea></label><div id="assessmentSpecific">'+assessmentSpecificFields(defaultArea)+'</div><label>Achados clínicos gerais<textarea name="findings" required placeholder="Integre os principais comportamentos, desempenhos, alterações, respostas e resultados observados"></textarea></label><div class="two"><label>Impressão / síntese clínica<textarea name="impression" placeholder="Síntese dos principais achados e hipóteses clínicas"></textarea></label><label>Conduta / próximos passos<textarea name="plan" placeholder="Objetivos terapêuticos, orientações, encaminhamentos e reavaliação"></textarea></label></div><label>Orientações à família / paciente<textarea name="guidance" placeholder="Orientações realizadas ao final da avaliação"></textarea></label><button class="primary">Salvar avaliação</button></form>');
  var areaSelect=document.getElementById('assessmentArea'),specific=document.getElementById('assessmentSpecific');
  areaSelect.onchange=function(){specific.innerHTML=assessmentSpecificFields(this.value);};
  document.getElementById('assessmentForm').onsubmit=function(e){e.preventDefault();var fd=new FormData(e.target),details={};fd.forEach(function(v,k){if(['kind','date','area','protocol','objective','findings','impression','plan'].indexOf(k)<0)details[k]=v;});var summary=[fd.get('objective')?'Objetivo: '+fd.get('objective'):'','Achados: '+fd.get('findings'),fd.get('impression')?'Síntese: '+fd.get('impression'):'',fd.get('plan')?'Conduta: '+fd.get('plan'):''].filter(Boolean).join('\n\n');data.assessments.push({id:id(),patientId:pid,kind:fd.get('kind'),date:fd.get('date'),area:fd.get('area'),protocol:fd.get('protocol'),objective:fd.get('objective'),findings:fd.get('findings'),impression:fd.get('impression'),plan:fd.get('plan'),details:details,summary:summary});save();document.getElementById('modal').remove();var pp=patient(pid);if(state.patient&&pp){app.innerHTML=patientView(pp);bind();}else render();};
}
function evolutionArea(p){var list=data.evolutions.filter(function(x){return x.patientId===p.id;}).sort(function(a,b){return (b.date||'').localeCompare(a.date||'');});modal('<small class="overline">EVOLUÇÕES</small><h2>'+esc(p.name)+'</h2><div class="modal-actions"><button class="primary" id="newEvolution">+ Nova evolução</button></div>'+(list.length?'<div class="record-list">'+list.map(function(x){return '<div class="clinical-record"><div><b>'+shortDate(x.date)+' · '+esc(x.focus||'Atendimento')+'</b><p>'+esc(x.text||'')+'</p><small>Conduta: '+esc(x.conduct||'—')+'</small></div></div>';}).join('')+'</div>':'<div class="empty">Nenhuma evolução registrada.</div>'));document.getElementById('newEvolution').onclick=function(){evolutionForm(p.id);};}
function evolutionForm(pid,appointment){
  appointment=appointment||null;
  var p=patient(pid),defaultFocus=p&&p.area||'Linguagem';
  modal('<small class="overline">SESSÃO CLÍNICA</small><h2>Registrar evolução</h2><form id="evolutionForm"><div class="two"><label>Data<input type="date" name="date" value="'+esc(appointment&&appointment.date||today())+'"></label><label>Foco da sessão<select name="focus">'+['Linguagem','Fala / Fonologia','Voz','Fluência','Motricidade Orofacial','Disfagia','Audiologia','CAA / Comunicação','Orientação familiar','Outro'].map(function(x){return '<option '+(x===defaultFocus?'selected':'')+'>'+x+'</option>';}).join('')+'</select></label></div><label>Objetivo da sessão<textarea name="objective" placeholder="O que foi priorizado neste atendimento?"></textarea></label><label>Atividades / estratégias utilizadas<textarea name="activities" placeholder="Recursos, tarefas, estratégias e estímulos utilizados"></textarea></label><label>Resposta do paciente / evolução<textarea name="text" required placeholder="Desempenho, respostas, facilidades, dificuldades e progresso observado"></textarea></label><div class="two"><label>Orientações / conduta<textarea name="conduct" placeholder="Orientações ao paciente/família e conduta"></textarea></label><label>Próximos objetivos<textarea name="next" placeholder="O que seguir trabalhando nas próximas sessões"></textarea></label></div><button class="primary">Salvar evolução</button></form>');
  document.getElementById('evolutionForm').onsubmit=function(e){e.preventDefault();var fd=new FormData(e.target);var fullText=[fd.get('objective')?'Objetivo: '+fd.get('objective'):'',fd.get('activities')?'Atividades: '+fd.get('activities'):'','Evolução: '+fd.get('text'),fd.get('next')?'Próximos objetivos: '+fd.get('next'):''].filter(Boolean).join('\n\n');data.evolutions.push({id:id(),patientId:pid,appointmentId:appointment&&appointment.id||null,date:fd.get('date'),focus:fd.get('focus'),objective:fd.get('objective'),activities:fd.get('activities'),text:fullText,conduct:fd.get('conduct'),next:fd.get('next')});if(appointment)appointment.status='Concluído';syncPackages();save();document.getElementById('modal').remove();var pp=patient(pid);if(state.patient&&pp){app.innerHTML=patientView(pp);bind();}else render();};
}
function documentsArea(p){var list=p.documents||[];modal('<small class="overline">DOCUMENTOS</small><h2>'+esc(p.name)+'</h2><div class="modal-actions"><button class="primary" id="newDocument">+ Adicionar documento</button></div>'+(list.length?'<div class="record-list">'+list.map(function(d){return documentRow(p,d);}).join('')+'</div>':'<div class="empty">Nenhum documento salvo.</div>'));document.getElementById('newDocument').onclick=function(){documentForm(p.id);};bindDocActions();}
function documentRow(p,d){return '<div class="clinical-record"><div><b>'+esc(d.title||d.fileName||'Documento')+'</b><small>'+esc(d.type||'Arquivo')+' · '+shortDate(d.date)+'</small><p>'+esc(d.note||'')+'</p></div><div class="record-actions">'+(d.dataUrl?'<button class="soft-btn" data-download-doc="'+p.id+'|'+d.id+'">Baixar</button>':'')+'<button class="danger-btn" data-delete-doc="'+p.id+'|'+d.id+'">Excluir</button></div></div>';}
function documentForm(pid){modal('<small class="overline">DOCUMENTO CLÍNICO</small><h2>Adicionar documento</h2><form id="docForm"><label>Título<input name="title" required></label><div class="two"><label>Tipo<select name="type"><option>Laudo</option><option>Exame</option><option>Foto</option><option>Vídeo</option><option>Áudio / amostra de fala</option><option>Parecer</option><option>TCLE</option><option>Outro</option></select></label><label>Data<input type="date" name="date" value="'+today()+'"></label></div><label>Arquivo<input type="file" id="docFile"></label><label>Observação<textarea name="note"></textarea></label><button class="primary">Salvar documento</button></form><p class="muted">Arquivos de até 2 MB ficam salvos neste navegador.</p>');document.getElementById('docForm').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),file=document.getElementById('docFile').files[0],p=patient(pid);if(!p)return;if(file&&file.size>2*1024*1024){alert('Para esta versão, use arquivos de até 2 MB.');return;}function finish(dataUrl){p.documents=p.documents||[];p.documents.push({id:id(),title:f.get('title'),type:f.get('type'),date:f.get('date'),note:f.get('note'),fileName:file?file.name:'',mime:file?file.type:'',dataUrl:dataUrl||''});try{save();document.getElementById('modal').remove();if(state.patient){app.innerHTML=patientView(p);bind();}else render();}catch(err){alert('O navegador ficou sem espaço para salvar este arquivo. Tente um arquivo menor.');}}if(file){var r=new FileReader();r.onload=function(){finish(r.result);};r.readAsDataURL(file);}else finish('');};}
function bindDocActions(){document.querySelectorAll('[data-download-doc]').forEach(function(b){b.onclick=function(){var parts=b.getAttribute('data-download-doc').split('|'),p=patient(parts[0]),d=p&&(p.documents||[]).find(function(x){return x.id===parts[1];});if(d&&d.dataUrl){var a=document.createElement('a');a.href=d.dataUrl;a.download=d.fileName||d.title||'documento';a.click();}};});document.querySelectorAll('[data-delete-doc]').forEach(function(b){b.onclick=function(){var parts=b.getAttribute('data-delete-doc').split('|'),p=patient(parts[0]);if(p&&confirm('Excluir este documento?')){p.documents=(p.documents||[]).filter(function(x){return x.id!==parts[1];});save();document.getElementById('modal')&&document.getElementById('modal').remove();if(state.patient){app.innerHTML=patientView(p);bind();}else render();}};});}
function finance(){
  syncPackages();
  var mk=today().slice(0,7),receivedMonth=data.payments.filter(function(x){return x.status==='Pago'&&monthKey(x.date)===mk;}).reduce(function(sum,x){return sum+Number(x.value||0);},0),
  pending=data.payments.filter(function(x){return x.status==='Pendente';}).reduce(function(sum,x){return sum+Number(x.value||0);},0),
  active=data.packages.filter(function(x){return x.status!=='Encerrado';}).length,
  paidMonth=data.payments.filter(function(x){return x.status==='Pago'&&monthKey(x.date)===mk;}),
  ticket=paidMonth.length?receivedMonth/paidMonth.length:0,
  pfilter=state.financePatient,
  packages=data.packages.filter(function(x){return !pfilter||x.patientId===pfilter;}),
  payments=data.payments.filter(function(x){return !pfilter||x.patientId===pfilter;}).sort(function(a,b){return (b.date||'').localeCompare(a.date||'');});
  var body='<div class="ffinance-stats"><article><small>RECEBIDO NO MÊS</small><b>'+money(receivedMonth)+'</b><span>'+paidMonth.length+' pagamento'+(paidMonth.length===1?'':'s')+'</span></article><article><small>PENDENTE</small><b>'+money(pending)+'</b><span>valores a receber</span></article><article><small>PACOTES ATIVOS</small><b>'+active+'</b><span>acompanhamentos</span></article><article><small>TICKET MÉDIO</small><b>'+money(ticket)+'</b><span>pagamentos do mês</span></article></div>'+
  '<article class="panel"><div class="tools"><select id="financeFilter"><option value="">Todos os pacientes</option>'+patientOptions(pfilter)+'</select><div class="tool-actions"><button id="newPackage" class="primary">+ Novo pacote</button><button id="newPayment" class="soft-btn">+ Pagamento</button></div></div><div class="fsection-title"><div><small>ACOMPANHAMENTO</small><h3>Pacotes e sessões</h3></div></div>'+
  (packages.length?'<div class="record-list">'+packages.map(function(p){var pct=Math.min(100,(Number(p.used||0)/Math.max(1,Number(p.sessions||1))*100));return '<div class="package-card fpackage-card"><div><b>'+esc(patientName(p.patientId))+' · '+esc(p.name||'Pacote')+'</b><span>'+Number(p.used||0)+' de '+Number(p.sessions||0)+' sessões utilizadas</span><div class="progress"><i style="width:'+pct+'%"></i></div><small>'+remainingPackage(p)+' restantes · '+esc(p.status||'Ativo')+'</small></div><strong>'+money(p.value)+'</strong></div>';}).join('')+'</div>':'<div class="empty">Nenhum pacote criado.</div>')+
  '<div class="fsection-title section-gap"><div><small>MOVIMENTAÇÕES</small><h3>Pagamentos</h3></div></div>'+
  (payments.length?'<div class="record-list">'+payments.map(function(p){return '<div class="clinical-record"><div><b>'+esc(patientName(p.patientId))+' · '+money(p.value)+'</b><small>'+shortDate(p.date)+' · '+esc(p.method||'Não informado')+'</small><p>'+esc(p.description||'Pagamento')+'</p></div><mark class="status-'+slug(p.status)+'">'+esc(p.status||'Pago')+'</mark></div>';}).join('')+'</div>':'<div class="empty">Nenhum pagamento lançado.</div>')+'</article>';
  return shell(body,'Financeiro','');
}
function packageForm(pid){if(!data.patients.length){alert('Cadastre um paciente primeiro.');return;}pid=pid||state.financePatient||data.patients[0].id;modal('<small class="overline">PACOTE</small><h2>Novo pacote</h2><form id="packageForm"><label>Paciente<select name="patientId">'+patientOptions(pid)+'</select></label><div class="two"><label>Nome do pacote<input name="name" placeholder="Ex.: Pacote mensal" required></label><label>Número de sessões<input type="number" min="1" name="sessions" value="4" required></label></div><div class="two"><label>Valor total<input type="number" step="0.01" min="0" name="value" required></label><label>Data de início<input type="date" name="startDate" value="'+today()+'"></label></div><label>Pagamento inicial<select name="paymentStatus"><option>Pago</option><option>Pendente</option></select></label><button class="primary">Criar pacote</button></form>');document.getElementById('packageForm').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target),pkg={id:id(),patientId:f.get('patientId'),name:f.get('name'),sessions:Number(f.get('sessions')),used:0,value:Number(f.get('value')),startDate:f.get('startDate'),status:'Ativo'};data.packages.push(pkg);data.payments.push({id:id(),patientId:pkg.patientId,packageId:pkg.id,value:pkg.value,date:pkg.startDate,method:'Pacote',description:'Pacote '+pkg.name,status:f.get('paymentStatus')});save();document.getElementById('modal').remove();state.page='financeiro';render();};}
function paymentForm(pid){if(!data.patients.length){alert('Cadastre um paciente primeiro.');return;}pid=pid||state.financePatient||data.patients[0].id;modal('<small class="overline">FINANCEIRO</small><h2>Novo pagamento</h2><form id="paymentForm"><label>Paciente<select name="patientId">'+patientOptions(pid)+'</select></label><div class="two"><label>Valor<input type="number" step="0.01" min="0" name="value" required></label><label>Data<input type="date" name="date" value="'+today()+'"></label></div><div class="two"><label>Forma<select name="method"><option>Pix</option><option>Dinheiro</option><option>Cartão</option><option>Transferência</option><option>Convênio</option><option>Outro</option></select></label><label>Status<select name="status"><option>Pago</option><option>Pendente</option></select></label></div><label>Descrição<input name="description" placeholder="Ex.: sessão avulsa"></label><button class="primary">Salvar pagamento</button></form>');document.getElementById('paymentForm').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);data.payments.push({id:id(),patientId:f.get('patientId'),value:Number(f.get('value')),date:f.get('date'),method:f.get('method'),status:f.get('status'),description:f.get('description')});save();document.getElementById('modal').remove();state.page='financeiro';render();};}
function financePatient(p){state.financePatient=p.id;state.page='financeiro';document.getElementById('modal')&&document.getElementById('modal').remove();render();}
function reportsPage(){
  var all=data.appointments.length,done=data.appointments.filter(function(a){return a.status==='Concluído';}).length,miss=data.appointments.filter(function(a){return a.status==='Faltou';}).length,cancel=data.appointments.filter(function(a){return a.status==='Cancelado';}).length,
  valid=done+miss,attendance=valid?Math.round(done/valid*100):0,docs=data.patients.reduce(function(sum,p){return sum+(p.documents||[]).length;},0),
  areas={};data.patients.forEach(function(p){areas[p.area||'Outra']=(areas[p.area||'Outra']||0)+1;});
  var ordered=Object.keys(areas).sort(function(a,b){return areas[b]-areas[a];}).slice(0,5);
  return shell('<div class="freports-hero"><div><small>VISÃO GERAL</small><h2>'+attendance+'%</h2><span>taxa de presença entre atendimentos concluídos e faltas</span></div><div class="freports-mini"><div><b>'+all+'</b><span>agendamentos</span></div><div><b>'+done+'</b><span>concluídos</span></div><div><b>'+miss+'</b><span>faltas</span></div><div><b>'+cancel+'</b><span>cancelamentos</span></div></div></div>'+
  '<div class="freports-grid"><article class="panel"><div class="panel-title"><div><small>PRODUÇÃO CLÍNICA</small><h3>Registros do Fonely</h3></div></div><div class="report-grid"><div><b>'+data.assessments.length+'</b><span>Avaliações registradas</span></div><div><b>'+data.evolutions.length+'</b><span>Evoluções registradas</span></div><div><b>'+data.packages.length+'</b><span>Pacotes criados</span></div><div><b>'+docs+'</b><span>Documentos salvos</span></div></div></article>'+
  '<article class="panel"><div class="panel-title"><div><small>CARTEIRA</small><h3>Pacientes por área</h3></div></div><div class="farea-list">'+(ordered.length?ordered.map(function(a){var pct=data.patients.length?Math.round(areas[a]/data.patients.length*100):0;return '<div><span><b>'+esc(a)+'</b><small>'+areas[a]+' paciente'+(areas[a]===1?'':'s')+'</small></span><em>'+pct+'%</em></div>';}).join(''):'<div class="empty">Sem pacientes cadastrados.</div>')+'</div></article></div>',
  'Relatórios','');
}
function teamPage(){return shell('<article class="panel"><div class="tools"><div><b>Profissionais</b><span class="muted">Equipe vinculada ao espaço</span></div><button id="newTeam" class="primary">+ Adicionar profissional</button></div>'+(data.team.length?'<div class="patient-list">'+data.team.map(function(t){return '<div class="patient"><div class="avatar">'+esc((t.name||'?').charAt(0))+'</div><div><b>'+esc(t.name)+'</b><span>'+esc(t.role||'Profissional')+' · '+esc(t.email||'')+'</span></div></div>';}).join('')+'</div>':'<div class="empty"><b>Nenhum profissional adicional</b><span>O espaço pode ser usado individualmente.</span></div>')+'</article>','Equipe','');}
function teamForm(){modal('<small class="overline">EQUIPE</small><h2>Adicionar profissional</h2><form id="teamForm"><label>Nome<input name="name" required></label><div class="two"><label>Função<input name="role" placeholder="Fonoaudiólogo(a)"></label><label>E-mail<input type="email" name="email"></label></div><button class="primary">Salvar profissional</button></form>');document.getElementById('teamForm').onsubmit=function(e){e.preventDefault();var f=new FormData(e.target);data.team.push({id:id(),name:f.get('name'),role:f.get('role'),email:f.get('email')});save();document.getElementById('modal').remove();render();};}
function academy(){return shell('<article class="academy"><div>✦</div><h2>Fonely <span>Academy</span></h2><p>Conteúdos e cursos para transformar conhecimento em prática clínica.</p><em>EM BREVE</em></article>','Fonely Academy','');}
function modal(html){var old=document.getElementById('modal');if(old)old.remove();var m=document.createElement('div');m.className='modal';m.id='modal';m.innerHTML='<div class="modal-card"><button class="close" id="closeModal">×</button>'+html+'</div>';document.body.appendChild(m);document.getElementById('closeModal').onclick=function(){m.remove();};}
function bindModalRows(){document.querySelectorAll('#modal [data-ap]').forEach(function(b){b.onclick=function(){var a=data.appointments.find(function(x){return x.id===b.getAttribute('data-ap');});if(a){document.getElementById('modal').remove();appointmentDetails(a);}};});}
function choosePatientFor(kind){if(!data.patients.length){newPatient(false);return;}modal('<small class="overline">SELECIONAR PACIENTE</small><h2>'+esc(kind==='assessment'?'Nova avaliação':'Nova evolução')+'</h2><label>Paciente<select id="choosePatient">'+patientOptions(data.patients[0].id)+'</select></label><button class="primary" id="confirmChoose">Continuar</button>');document.getElementById('confirmChoose').onclick=function(){var pid=document.getElementById('choosePatient').value;kind==='assessment'?assessmentForm(pid):evolutionForm(pid);};}
function choosePatientForDocument(){if(!data.patients.length){newPatient(false);return;}modal('<small class="overline">DOCUMENTO</small><h2>Selecionar paciente</h2><label>Paciente<select id="chooseDocPatient">'+patientOptions(data.patients[0].id)+'</select></label><button class="primary" id="confirmDocPatient">Continuar</button>');document.getElementById('confirmDocPatient').onclick=function(){documentForm(document.getElementById('chooseDocPatient').value);};}
function bind(){
  document.querySelectorAll('[data-go]').forEach(function(b){b.onclick=function(){state.page=b.getAttribute('data-go');state.patient=null;render();};});
  document.querySelectorAll('[data-patient]').forEach(function(b){b.onclick=function(){state.patient=b.getAttribute('data-patient');var p=patient(state.patient);if(p){app.innerHTML=patientView(p);bind();}};});
  document.querySelectorAll('[data-parea]').forEach(function(b){b.onclick=function(){var p=patient(state.patient),area=b.getAttribute('data-parea');if(!p)return;if(area==='anam')anamnesis(p);if(area==='assess')assessmentArea(p);if(area==='evol')evolutionArea(p);if(area==='docs')documentsArea(p);if(area==='fin')financePatient(p);if(area==='reports'){state.page='relatorios';render();}};});
  document.querySelectorAll('[data-ap]').forEach(function(b){b.onclick=function(){var a=data.appointments.find(function(x){return x.id===b.getAttribute('data-ap');});if(a)appointmentDetails(a);};});
  document.querySelectorAll('[data-day]').forEach(function(b){b.onclick=function(){dayModal(b.getAttribute('data-day'));};});
  document.querySelectorAll('[data-home-go]').forEach(function(b){b.onclick=function(){state.page=b.getAttribute('data-home-go');state.patient=null;render();};});
  document.querySelectorAll('[data-home-list]').forEach(function(b){b.onclick=function(){var mode=b.getAttribute('data-home-list'),list=appointmentsForDate(today());if(mode==='done')list=list.filter(function(a){return a.status==='Concluído';});modal('<small class="overline">'+(mode==='done'?'CONCLUÍDOS HOJE':'ATENDIMENTOS DE HOJE')+'</small><h2>'+esc(parseDate(today()).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'}))+'</h2>'+appointmentRows(list)+'<div class="modal-actions"><button class="soft-btn" id="homeOpenAgenda">Abrir agenda completa</button></div>');var go=document.getElementById('homeOpenAgenda');if(go)go.onclick=function(){document.getElementById('modal').remove();state.page='agenda';state.agendaDate=today();render();};bindModalRows();};});
  var np=document.getElementById('newPatient');if(np)np.onclick=function(){newPatient(false);};
  var na=document.getElementById('newAppointment');if(na)na.onclick=function(){newAppointment(null,today());};
  var hna=document.getElementById('homeNewAppointment');if(hna)hna.onclick=function(){newAppointment(null,today());};
  var sp=document.getElementById('schedulePatient');if(sp)sp.onclick=function(){newAppointment(state.patient,today());};
  var pna=document.getElementById('patientNewAssessment');if(pna)pna.onclick=function(){assessmentForm(state.patient);};
  var pne=document.getElementById('patientNewEvolution');if(pne)pne.onclick=function(){evolutionForm(state.patient);};
  var pnd=document.getElementById('patientNewDocument');if(pnd)pnd.onclick=function(){documentForm(state.patient);};
  var ps=document.getElementById('patientSearch');if(ps)ps.oninput=function(){var q=ps.value.toLowerCase();document.getElementById('patientList').innerHTML=patientList(data.patients.filter(function(p){return [p.name,p.area,p.guardian].join(' ').toLowerCase().indexOf(q)>=0;}));document.querySelectorAll('[data-patient]').forEach(function(b){b.onclick=function(){state.patient=b.getAttribute('data-patient');var p=patient(state.patient);if(p){app.innerHTML=patientView(p);bind();}};});};
  var prev=document.getElementById('agendaPrev'),next=document.getElementById('agendaNext'),at=document.getElementById('agendaToday');
  if(prev)prev.onclick=function(){var d=parseDate(state.agendaDate);d.setMonth(d.getMonth()-1);state.agendaDate=dateKey(d);render();};
  if(next)next.onclick=function(){var d2=parseDate(state.agendaDate);d2.setMonth(d2.getMonth()+1);state.agendaDate=dateKey(d2);render();};
  if(at)at.onclick=function(){state.agendaDate=today();render();};
  var nc=document.getElementById('newClinical');if(nc)nc.onclick=function(){choosePatientFor(nc.getAttribute('data-kind'));};
  var nd=document.getElementById('newGlobalDocument');if(nd)nd.onclick=choosePatientForDocument;
  var nf=document.getElementById('financeFilter');if(nf){nf.value=state.financePatient||'';nf.onchange=function(){state.financePatient=this.value||null;render();};}
  var pkg=document.getElementById('newPackage');if(pkg)pkg.onclick=function(){packageForm();};
  var pay=document.getElementById('newPayment');if(pay)pay.onclick=function(){paymentForm();};
  var nt=document.getElementById('newTeam');if(nt)nt.onclick=teamForm;
  var accountButton=document.getElementById('accountMenu');
  if(accountButton&&window.FonelyAccountUI){accountButton.onclick=function(){window.FonelyAccountUI.open();};}

  bindDocActions();
}
syncPackages();save();render();
})();